debug: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?characterEncoding=utf-8&useSSL=false
    username: fanroot
    password: fanRoot
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      # 页面默认前缀目录
      prefix: /WEB-INF/jsp/
      # 响应页面默认后缀
      suffix: .jsp
  redis:
    #redis 数据库索引
    database: 0
    #redis服务器地址
    host: localhost
    #端口号
    port: 6379
    #密码
    password: password
    pool:
      #连接池最大连接数
      max-active: 8
      #最长等待时间（使用负值表示没有限制）
      max-wait: -1
     #最大空闲数
      max-idle: 8
      #最小空闲数
      min-idle: 0
      #连接超时时间
    timeout: 0


